package main

import (
	"context"
	"fmt"
	"strconv"
	"sync/atomic"
	"time"

	goredis "github.com/redis/go-redis/v9"
)

// RedisQuerier implements LedgerMutator using Redis sorted sets.
//
// Key schema:
//   - acp:req:{agentID}        → ZSet, score = Unix nanoseconds
//   - acp:denial:{agentID}     → ZSet, score = Unix nanoseconds
//   - acp:pattern:{patternKey} → ZSet, score = Unix nanoseconds
//   - acp:cooldown:{agentID}   → String, value = Unix nanoseconds of expiry
//
// Members in each ZSet are unique strings generated by an atomic counter.
// Use Flush() between experiment runs to clear all ACP keys.
type RedisQuerier struct {
	client  *goredis.Client
	counter int64 // atomic member ID generator; ensures unique ZSet members
}

// Verify at compile time that *RedisQuerier implements LedgerMutator.
var _ LedgerMutator = (*RedisQuerier)(nil)

// NewRedisQuerier connects to Redis at addr and verifies connectivity.
// Returns an error if the PING fails.
func NewRedisQuerier(addr string) (*RedisQuerier, error) {
	c := goredis.NewClient(&goredis.Options{Addr: addr})
	if err := c.Ping(context.Background()).Err(); err != nil {
		_ = c.Close()
		return nil, fmt.Errorf("redis ping failed: %w", err)
	}
	return &RedisQuerier{client: c}, nil
}

// Close closes the underlying Redis connection.
func (q *RedisQuerier) Close() error {
	return q.client.Close()
}

// Flush deletes all acp:* keys. Call between experiment runs.
func (q *RedisQuerier) Flush() {
	ctx := context.Background()
	keys, err := q.client.Keys(ctx, "acp:*").Result()
	if err != nil || len(keys) == 0 {
		return
	}
	q.client.Del(ctx, keys...)
}

// nextMember returns a unique string member for ZSet entries.
func (q *RedisQuerier) nextMember() string {
	return strconv.FormatInt(atomic.AddInt64(&q.counter, 1), 10)
}

func (q *RedisQuerier) zadd(key string, score float64) {
	q.client.ZAdd(context.Background(), key, goredis.Z{
		Score:  score,
		Member: q.nextMember(),
	})
}

func (q *RedisQuerier) zcount(key string, minNs, maxNs int64) int64 {
	n, _ := q.client.ZCount(context.Background(), key,
		strconv.FormatInt(minNs, 10),
		strconv.FormatInt(maxNs, 10),
	).Result()
	return n
}

// ── LedgerQuerier (read) ──────────────────────────────────────────────────────

func (q *RedisQuerier) CountRequests(agentID string, window time.Duration, now time.Time) (int, error) {
	cutoff := now.Add(-window)
	return int(q.zcount("acp:req:"+agentID, cutoff.UnixNano(), now.UnixNano())), nil
}

func (q *RedisQuerier) CountDenials(agentID string, since time.Time) (int, error) {
	return int(q.zcount("acp:denial:"+agentID, since.UnixNano(), time.Now().UnixNano())), nil
}

func (q *RedisQuerier) CountPattern(patternKey string, since time.Time) (int, error) {
	return int(q.zcount("acp:pattern:"+patternKey, since.UnixNano(), time.Now().UnixNano())), nil
}

func (q *RedisQuerier) CooldownActive(agentID string, now time.Time) bool {
	val, err := q.client.Get(context.Background(), "acp:cooldown:"+agentID).Result()
	if err != nil {
		return false // key missing → not in cooldown
	}
	untilNs, err := strconv.ParseInt(val, 10, 64)
	if err != nil {
		return false
	}
	return now.UnixNano() < untilNs
}

func (q *RedisQuerier) CooldownUntil(agentID string) time.Time {
	val, err := q.client.Get(context.Background(), "acp:cooldown:"+agentID).Result()
	if err != nil {
		return time.Time{}
	}
	ns, err := strconv.ParseInt(val, 10, 64)
	if err != nil {
		return time.Time{}
	}
	return time.Unix(0, ns)
}

// ── Mutation methods ──────────────────────────────────────────────────────────

func (q *RedisQuerier) AddRequest(agentID string, t time.Time) {
	q.zadd("acp:req:"+agentID, float64(t.UnixNano()))
}

func (q *RedisQuerier) AddDenial(agentID string, t time.Time) {
	q.zadd("acp:denial:"+agentID, float64(t.UnixNano()))
}

func (q *RedisQuerier) AddPattern(patternKey string, t time.Time) {
	q.zadd("acp:pattern:"+patternKey, float64(t.UnixNano()))
}

func (q *RedisQuerier) SetCooldown(agentID string, until time.Time) {
	ttl := time.Until(until) + time.Minute // key lives slightly longer than cooldown
	q.client.Set(context.Background(),
		"acp:cooldown:"+agentID,
		strconv.FormatInt(until.UnixNano(), 10),
		ttl,
	)
}
